name: absenqu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.4.1
  provider: 6.0.5
  firebase_auth: 4.2.5
  loading_animation_widget: 1.2.0+4
  flutter_svg: 1.0.3
  cloud_firestore: 4.3.1
  intl: 0.17.0
  flutter_slidable: 2.0.0
  geolocator: 9.0.2
  geocoding: 2.0.5
  maps_launcher: 2.0.1
  firebase_storage: 11.0.10
  image_picker: ^0.8.6+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/app/data/assets/images/splash.png"

flutter:
  assets:
    - lib/app/data/assets/images/
    - lib/app/data/assets/icons/
  fonts:
    - family: inter
      fonts:
        - asset: lib/app/data/assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: lib/app/data/assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: lib/app/data/assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/app/data/assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: lib/app/data/assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/app/data/assets/fonts/inter/Inter-Black.ttf
          weight: 900
    - family: montserrat
      fonts:
        - asset: lib/app/data/assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/app/data/assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/app/data/assets/fonts/montserrat/Montserrat-Italic.ttf
          weight: 600
        - asset: lib/app/data/assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/app/data/assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
  uses-material-design: true
